### ISSUE TITLE
Kerberos/SPNEGO Support

### ISSUE THREAD

**Issue by rhblind** [open-status/ex_curl#3]
Hey,
This is an interesting project. If `libcurl` is compiled with Kerberos/SPNEGO support, will this be supported out of the box?

**Comment by danielrudn** [comment]
Hey, I created a pull request (#5) that introduces a new `http_auth_negotiate` option to enable Kerberos/SPNEGO-based authenticated when it is supported by libcurl.

To be honest, I am not very familiar with Kerberos/SPNEGO so I followed the steps [here](https://stackoverflow.com/a/38664954) to implement and test this functionality. I haven't tested it with a production deployment that uses Kerberos/SPNEGO for authentication.
